// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui_helpers.h"

#define UI_NAV_CACHE_MAX 3

static ui_nav_entry_t ui_nav_registry[16];
static uint8_t ui_nav_registry_len;

static ui_nav_entry_t ui_nav_stack[16];
static uint8_t ui_nav_stack_len;

static lv_obj_t ** ui_nav_cache[UI_NAV_CACHE_MAX];
static uint8_t ui_nav_cache_len;

/* 添加时间: 2026-08-19
 * 原因: 点击回调里不能直接切页。
 * 逻辑: 用 lv_async_call 把 push/back 排到 LVGL 事件处理完之后；连点同一目标只跳一次。 */
typedef enum {
    UI_NAV_ASYNC_NONE = 0,
    UI_NAV_ASYNC_PUSH,
    UI_NAV_ASYNC_BACK,
} ui_nav_async_kind_t;

static ui_nav_async_kind_t s_nav_async_kind;
static lv_obj_t ** s_nav_async_target;

static void ui_nav_async_cb(void * user_data);

static void ui_nav_async_cancel_pending(void)
{
    lv_async_call_cancel(ui_nav_async_cb, NULL);
    s_nav_async_kind = UI_NAV_ASYNC_NONE;
    s_nav_async_target = NULL;
}

static bool ui_nav_keep_requested_anim(lv_obj_t ** current, lv_obj_t ** target, lv_screen_load_anim_t requested)
{
    if(current != &ui_StandbyScreen) return false;
    if(target != &ui_HomeScreen) return false;
    return requested == LV_SCR_LOAD_ANIM_MOVE_TOP;
}

static lv_screen_load_anim_t ui_nav_resolve_anim(lv_obj_t ** current, lv_obj_t ** target,
                                                 lv_screen_load_anim_t requested)
{
    if(requested == LV_SCR_LOAD_ANIM_NONE) return LV_SCR_LOAD_ANIM_NONE;
    if(ui_nav_keep_requested_anim(current, target, requested)) return requested;
    return LV_SCR_LOAD_ANIM_NONE;
}

static int ui_nav_resolve_speed(lv_obj_t ** current, lv_obj_t ** target,
                                lv_screen_load_anim_t requested, int speed)
{
    if(ui_nav_keep_requested_anim(current, target, requested)) return speed;
    return 0;
}

static int ui_nav_resolve_delay(lv_obj_t ** current, lv_obj_t ** target,
                                lv_screen_load_anim_t requested, int delay)
{
    if(ui_nav_keep_requested_anim(current, target, requested)) return delay;
    return 0;
}

static const ui_nav_entry_t * ui_nav_find_by_pp(lv_obj_t ** pp)
{
    for(uint8_t i = 0; i < ui_nav_registry_len; i++) {
        if(ui_nav_registry[i].screen == pp) return &ui_nav_registry[i];
    }
    return NULL;
}

static const ui_nav_entry_t * ui_nav_find_by_screen(lv_obj_t * scr)
{
    for(uint8_t i = 0; i < ui_nav_registry_len; i++) {
        if(ui_nav_registry[i].screen && *ui_nav_registry[i].screen == scr) return &ui_nav_registry[i];
    }
    return NULL;
}

static bool ui_nav_cache_contains(lv_obj_t ** pp)
{
    for(uint8_t i = 0; i < ui_nav_cache_len; i++) {
        if(ui_nav_cache[i] == pp) return true;
    }
    return false;
}

static bool ui_nav_cache_is_pinned(lv_obj_t ** pp)
{
    /* 添加时间: 2026-08-19
     * 原因: 栏目轮流进出时 FIFO 会把主界面踢出缓存并 deinit，返回时整页重建容易卡死。
     * 逻辑: 只钉住主界面指针，其它页仍按原 FIFO 淘汰，进出栏目的目标页不变。 */
    return pp == &ui_HomeScreen;
}

static void ui_nav_cache_add(lv_obj_t ** pp)
{
    if(!pp) return;
    if(ui_nav_cache_contains(pp)) return;
    if(ui_nav_cache_len >= UI_NAV_CACHE_MAX) {
        uint8_t evict_i = 0;
        while(evict_i < ui_nav_cache_len && ui_nav_cache_is_pinned(ui_nav_cache[evict_i])) {
            evict_i++;
        }
        if(evict_i >= ui_nav_cache_len) {
            return;
        }
        lv_obj_t ** evict = ui_nav_cache[evict_i];
        if(evict && *evict) {
            const ui_nav_entry_t * ent = ui_nav_find_by_pp(evict);
            if(ent && ent->deinit) ent->deinit();
        }
        for(uint8_t i = evict_i + 1; i < ui_nav_cache_len; i++) {
            ui_nav_cache[i - 1] = ui_nav_cache[i];
        }
        ui_nav_cache_len--;
    }
    ui_nav_cache[ui_nav_cache_len++] = pp;
}

static void ui_nav_cache_remove(lv_obj_t ** pp)
{
    for(uint8_t i = 0; i < ui_nav_cache_len; i++) {
        if(ui_nav_cache[i] == pp) {
            for(uint8_t j = i + 1; j < ui_nav_cache_len; j++)
                ui_nav_cache[j - 1] = ui_nav_cache[j];
            ui_nav_cache_len--;
            return;
        }
    }
}

void ui_make_decor_hit_passthrough(lv_obj_t * obj)
{
    if(!obj) return;
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(obj, LV_OBJ_FLAG_EVENT_BUBBLE);
}

void ui_nav_reset(void)
{
    ui_nav_async_cancel_pending();
    ui_nav_stack_len = 0;
    ui_nav_cache_len = 0;
}

void ui_nav_register(lv_obj_t ** screen, void (*init)(void), void (*deinit)(void))
{
    for(uint8_t i = 0; i < ui_nav_registry_len; i++) {
        if(ui_nav_registry[i].screen == screen) {
            ui_nav_registry[i].init = init;
            ui_nav_registry[i].deinit = deinit;
            return;
        }
    }

    if(ui_nav_registry_len >= (uint8_t)(sizeof(ui_nav_registry) / sizeof(ui_nav_registry[0]))) return;
    ui_nav_registry[ui_nav_registry_len].screen = screen;
    ui_nav_registry[ui_nav_registry_len].init = init;
    ui_nav_registry[ui_nav_registry_len].deinit = deinit;
    ui_nav_registry_len++;
}

void ui_nav_push(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay)
{
    /* 添加时间: 2026-08-19
     * 原因: 电源键/闹钟等同步切页若晚于点击排队，会把用户刚点的页再切走。
     * 逻辑: 真正执行 push 前取消未执行的异步导航，业务仍走下面原有入栈+切页。 */
    ui_nav_async_cancel_pending();

    const ui_nav_entry_t * target_ent = ui_nav_find_by_pp(target);
    if(!target_ent || !target_ent->init) return;

    lv_obj_t * cur_scr = lv_screen_active();
    const ui_nav_entry_t * cur_ent = ui_nav_find_by_screen(cur_scr);
    lv_obj_t ** cur_screen_pp = cur_ent ? cur_ent->screen : NULL;
    lv_screen_load_anim_t anim = ui_nav_resolve_anim(cur_screen_pp, target, fademode);

    if(cur_ent && cur_ent->screen && cur_ent->screen != target) {
        if(ui_nav_stack_len < (uint8_t)(sizeof(ui_nav_stack) / sizeof(ui_nav_stack[0]))) {
            ui_nav_stack[ui_nav_stack_len++] = *cur_ent;
        }
        ui_nav_cache_add(cur_ent->screen);
    }

    _ui_screen_change(target, anim, ui_nav_resolve_speed(cur_screen_pp, target, fademode, spd),
                      ui_nav_resolve_delay(cur_screen_pp, target, fademode, delay), target_ent->init);
}

bool ui_nav_back(lv_screen_load_anim_t fademode, int spd, int delay)
{
    ui_nav_async_cancel_pending();

    if(ui_nav_stack_len == 0) return false;

    lv_obj_t * cur_scr = lv_screen_active();
    const ui_nav_entry_t * cur_ent = ui_nav_find_by_screen(cur_scr);

    ui_nav_entry_t prev = ui_nav_stack[--ui_nav_stack_len];
    if(prev.screen == NULL || prev.init == NULL) return false;
    lv_obj_t ** cur_screen_pp = cur_ent ? cur_ent->screen : NULL;
    lv_screen_load_anim_t anim = ui_nav_resolve_anim(cur_screen_pp, prev.screen, fademode);

    if(cur_ent && cur_ent->screen) {
        ui_nav_cache_add(cur_ent->screen);
    }

    _ui_screen_change(prev.screen, anim, ui_nav_resolve_speed(cur_screen_pp, prev.screen, fademode, spd),
                      ui_nav_resolve_delay(cur_screen_pp, prev.screen, fademode, delay), prev.init);

    return true;
}

static void ui_nav_async_cb(void * user_data)
{
    (void)user_data;
    ui_nav_async_kind_t kind = s_nav_async_kind;
    lv_obj_t ** target = s_nav_async_target;
    s_nav_async_kind = UI_NAV_ASYNC_NONE;
    s_nav_async_target = NULL;

    if(kind == UI_NAV_ASYNC_PUSH) {
        ui_nav_push(target, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    } else if(kind == UI_NAV_ASYNC_BACK) {
        (void)ui_nav_back(LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

void ui_nav_push_async(lv_obj_t ** target)
{
    /* 添加时间: 2026-08-19
     * 原因: 松手回调不能同步切页。
     * 逻辑: 把原来的 ui_nav_push(target, NONE, 0, 0) 排到事件后；同一目标连点合并为一次。 */
    if(!target) return;
    if(s_nav_async_kind == UI_NAV_ASYNC_PUSH && s_nav_async_target == target) {
        return;
    }
    lv_async_call_cancel(ui_nav_async_cb, NULL);
    s_nav_async_kind = UI_NAV_ASYNC_PUSH;
    s_nav_async_target = target;
    lv_async_call(ui_nav_async_cb, NULL);
}

void ui_nav_back_async(void)
{
    /* 添加时间: 2026-08-19
     * 原因: 返回同样不能在触摸事件里同步切页。
     * 逻辑: 排队调用原来的 ui_nav_back(NONE, 0, 0)，重复返回合并为一次。 */
    if(s_nav_async_kind == UI_NAV_ASYNC_BACK) {
        return;
    }
    lv_async_call_cancel(ui_nav_async_cb, NULL);
    s_nav_async_kind = UI_NAV_ASYNC_BACK;
    s_nav_async_target = NULL;
    lv_async_call(ui_nav_async_cb, NULL);
}

void ui_nav_invalidate(lv_obj_t ** target)
{
    ui_nav_cache_remove(target);
    const ui_nav_entry_t * ent = ui_nav_find_by_pp(target);
    if(ent && ent->deinit) ent->deinit();
}

void _ui_bar_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM) lv_bar_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_BAR_PROPERTY_VALUE) lv_bar_set_value(target, val, LV_ANIM_OFF);
}

void _ui_basic_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BASIC_PROPERTY_POSITION_X) lv_obj_set_x(target, val);
    if(id == _UI_BASIC_PROPERTY_POSITION_Y) lv_obj_set_y(target, val);
    if(id == _UI_BASIC_PROPERTY_WIDTH) lv_obj_set_width(target, val);
    if(id == _UI_BASIC_PROPERTY_HEIGHT) lv_obj_set_height(target, val);
}


void _ui_dropdown_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_DROPDOWN_PROPERTY_SELECTED) lv_dropdown_set_selected(target, val);
}

void _ui_image_set_property(lv_obj_t * target, int id, uint8_t * val)
{
    if(id == _UI_IMAGE_PROPERTY_IMAGE) lv_image_set_src(target, val);
}

void _ui_label_set_property(lv_obj_t * target, int id, const char * val)
{
    if(id == _UI_LABEL_PROPERTY_TEXT) lv_label_set_text(target, val);
}


void _ui_roller_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM) lv_roller_set_selected(target, val, LV_ANIM_ON);
    if(id == _UI_ROLLER_PROPERTY_SELECTED) lv_roller_set_selected(target, val, LV_ANIM_OFF);
}

void _ui_slider_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM) lv_slider_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_SLIDER_PROPERTY_VALUE) lv_slider_set_value(target, val, LV_ANIM_OFF);
}


void _ui_screen_change(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay,
                       void (*target_init)(void))
{
    /* 添加时间: 2026-08-19
     * 原因: 触摸事件未结束时 lv_indev_reset(NULL,NULL) 再切页，会把 LVGL 输入状态打乱导致假死。
     * 逻辑: 仍在输入事件中则跳过复位；事件已结束（电源键/异步回调/定时器）则保持原来的全设备复位。切页目标与动画参数不变。 */
    if(lv_indev_get_act() == NULL) {
        lv_indev_reset(NULL, NULL);
    }

    if(*target == NULL)
        target_init();
    if(fademode == LV_SCR_LOAD_ANIM_NONE) {
        lv_screen_load(*target);
        return;
    }

    lv_screen_load_anim(*target, fademode, spd, delay, false);
}

void _ui_screen_delete(lv_obj_t ** target)
{
    if(*target != NULL) {
        lv_obj_delete(*target);
        *target = NULL;
    }
}

void _ui_arc_increment(lv_obj_t * target, int val)
{
    int old = lv_arc_get_value(target);
    lv_arc_set_value(target, old + val);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

void _ui_bar_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_bar_get_value(target);
    lv_bar_set_value(target, old + val, anm);
}

void _ui_slider_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_slider_get_value(target);
    lv_slider_set_value(target, old + val, anm);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

void _ui_flag_modify(lv_obj_t * target, int32_t flag, int value)
{
    if(value == _UI_MODIFY_FLAG_TOGGLE) {
        if(lv_obj_has_flag(target, flag)) lv_obj_remove_flag(target, flag);
        else lv_obj_add_flag(target, flag);
    }
    else if(value == _UI_MODIFY_FLAG_ADD) lv_obj_add_flag(target, flag);
    else lv_obj_remove_flag(target, flag);
}
void _ui_state_modify(lv_obj_t * target, int32_t state, int value)
{
    if(value == _UI_MODIFY_STATE_TOGGLE) {
        if(lv_obj_has_state(target, state)) lv_obj_remove_state(target, state);
        else lv_obj_add_state(target, state);
    }
    else if(value == _UI_MODIFY_STATE_ADD) lv_obj_add_state(target, state);
    else lv_obj_remove_state(target, state);
}


void _ui_textarea_move_cursor(lv_obj_t * target, int val)

{

    if(val == UI_MOVE_CURSOR_UP) lv_textarea_cursor_up(target);
    if(val == UI_MOVE_CURSOR_RIGHT) lv_textarea_cursor_right(target);
    if(val == UI_MOVE_CURSOR_DOWN) lv_textarea_cursor_down(target);
    if(val == UI_MOVE_CURSOR_LEFT) lv_textarea_cursor_left(target);
    lv_obj_add_state(target, LV_STATE_FOCUSED);
}

void scr_unloaded_delete_cb(lv_event_t * e)

{

    lv_obj_t ** var = lv_event_get_user_data(e);
    lv_obj_delete(*var);
    (*var) = NULL;

}

void _ui_opacity_set(lv_obj_t * target, int val)
{
    lv_obj_set_style_opa(target, val, 0);
}

void _ui_anim_callback_free_user_data(lv_anim_t * a)
{
    lv_free(a->user_data);
    a->user_data = NULL;
}

void _ui_anim_callback_set_x(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_x(usr->target, v);

}


void _ui_anim_callback_set_y(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_y(usr->target, v);

}


void _ui_anim_callback_set_width(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_width(usr->target, v);

}


void _ui_anim_callback_set_height(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_height(usr->target, v);

}


void _ui_anim_callback_set_opacity(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_style_opa(usr->target, v, 0);

}


void _ui_anim_callback_set_image_zoom(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_scale(usr->target, v);

}


void _ui_anim_callback_set_image_angle(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_rotation(usr->target, v);

}


void _ui_anim_callback_set_image_frame(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    usr->val = v;

    if(v < 0) v = 0;
    if(v >= usr->imgset_size) v = usr->imgset_size - 1;
    lv_image_set_src(usr->target, usr->imgset[v]);
}

int32_t _ui_anim_callback_get_x(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_x_aligned(usr->target);

}


int32_t _ui_anim_callback_get_y(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_y_aligned(usr->target);

}


int32_t _ui_anim_callback_get_width(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_width(usr->target);

}


int32_t _ui_anim_callback_get_height(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_height(usr->target);

}


int32_t _ui_anim_callback_get_opacity(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_style_opa(usr->target, 0);

}

int32_t _ui_anim_callback_get_image_zoom(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_scale(usr->target);

}

int32_t _ui_anim_callback_get_image_angle(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_rotation(usr->target);

}

int32_t _ui_anim_callback_get_image_frame(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return usr->val;

}

void _ui_arc_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_arc_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}

void _ui_slider_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_slider_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}
void _ui_checked_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * txt_on, const char * txt_off)
{
    if(lv_obj_has_state(src, LV_STATE_CHECKED)) lv_label_set_text(trg, txt_on);
    else lv_label_set_text(trg, txt_off);
}


void _ui_switch_theme(int val)

{

#ifdef UI_THEME_ACTIVE
    ui_theme_set(val);
#endif
}


