#!/usr/bin/env python3
"""Generate ARGB8888 LVGL 9 image blobs for Waveshare 1.85 status bar (WiFi + battery)."""
from __future__ import annotations

import math
import os

W = H = 22
CF_ARGB8888 = 0x10
MAGIC = 0x19


def new_buf():
    return bytearray(W * H * 4)


def set_px(buf, x, y, a, r, g, b):
    if 0 <= x < W and 0 <= y < H:
        i = (y * W + x) * 4
        buf[i : i + 4] = bytes((b, g, r, a))


def draw_wifi(buf, bars: int):
    """bars: 1 weak (one arc), 2 fair, 3 strong — inner arcs first."""
    cx, cy = W // 2, H - 3
    for bi in range(bars):
        r = 4 + bi * 2
        for deg in range(200, 341, 1):
            rad = math.radians(deg)
            x = int(cx + r * math.cos(rad))
            y = int(cy - r * math.sin(rad))
            for dx in (-1, 0, 1):
                for dy in (-1, 0, 1):
                    set_px(buf, x + dx, y + dy, 255, 255, 255, 255)


def draw_wifi_slash(buf):
    for t in range(-2, 3):
        for i in range(W):
            x = i
            y = int(8 + i * 0.55) + t
            set_px(buf, x, y, 255, 255, 90, 90)
            set_px(buf, x, y + 1, 255, 255, 90, 90)


def draw_battery(buf, level: int, charging: bool):
    """level 0..4 fill bars; charging overlays bolt."""
    x0, y0, x1, y1 = 3, 5, 16, 15
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            if x == x0 or x == x1 or y == y0 or y == y1:
                set_px(buf, x, y, 255, 220, 220, 220)
    for y in range(y0 + 4, y1 - 3):
        set_px(buf, x1 + 1, y, 255, 220, 220, 220)
    for y in range(y0 + 1, y1):
        for x in range(x0 + 1, x1):
            set_px(buf, x, y, 0, 0, 0, 0)
    inner_x0 = x0 + 2
    inner_x1 = x1 - 1
    inner_w = inner_x1 - inner_x0
    segs = 5
    seg_w = max(1, inner_w // segs)
    for seg in range(level + 1):
        x_start = inner_x0 + seg * seg_w
        x_end = min(inner_x0 + (seg + 1) * seg_w, inner_x1)
        g = 70 + seg * 35
        for y in range(y0 + 2, y1 - 1):
            for x in range(x_start, x_end):
                set_px(buf, x, y, 255, 50, min(g, 230), 90)
    if charging:
        for i in range(7):
            set_px(buf, 9, 6 + i, 255, 255, 210, 50)
            set_px(buf, 10, 6 + i, 255, 255, 210, 50)


def c_array(name: str, data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hexes},")
    return f"static const uint8_t {name}[] = {{\n" + "\n".join(lines) + "\n};\n"


def emit_dsc(name: str, arr_name: str, nbytes: int) -> str:
    return f"""const lv_image_dsc_t {name} = {{
    .header = {{
        .magic = {MAGIC},
        .cf = {CF_ARGB8888},
        .flags = 0,
        .w = {W},
        .h = {H},
        .stride = {W * 4},
        .reserved_2 = 0,
    }},
    .data_size = {nbytes},
    .data = {arr_name},
    .reserved = NULL,
    .reserved_2 = NULL,
}};
"""


def main():
    out_c = os.path.join(
        os.path.dirname(__file__),
        "..",
        "main",
        "boards",
        "waveshare",
        "esp32-s3-touch-lcd-1.85",
        "waveshare_185_status_icons.c",
    )
    out_h = os.path.join(
        os.path.dirname(__file__),
        "..",
        "main",
        "boards",
        "waveshare",
        "esp32-s3-touch-lcd-1.85",
        "waveshare_185_status_icons.h",
    )

    images = []

    # WiFi variants
    for key, bars in [
        ("wifi_weak", 1),
        ("wifi_fair", 2),
        ("wifi_strong", 3),
    ]:
        b = new_buf()
        draw_wifi(b, bars)
        images.append((key, bytes(b)))

    b = new_buf()
    draw_wifi_slash(b)
    images.append(("wifi_slash", bytes(b)))

    # Battery 0..4 + charge
    for lv in range(5):
        b = new_buf()
        draw_battery(b, lv, False)
        images.append((f"bat_{lv}", bytes(b)))
    b = new_buf()
    draw_battery(b, 4, True)
    images.append(("bat_charge", bytes(b)))

    parts = [
        '/* Auto-generated by scripts/gen_waveshare185_status_icons.py */\n',
        '#include "waveshare_185_status_icons.h"\n',
        '#include <lvgl.h>\n\n',
    ]
    decls = [
        "#pragma once\n",
        "#include <lvgl.h>\n\n",
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n",
    ]

    for key, data in images:
        arr = f"img_{key}_map"
        parts.append(c_array(arr, data))
        parts.append(emit_dsc(f"waveshare185_{key}", arr, len(data)))
        parts.append("\n")
        decls.append(f"extern const lv_image_dsc_t waveshare185_{key};\n")

    decls.append("\n#ifdef __cplusplus\n}\n#endif\n")

    with open(out_c, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(parts))
    with open(out_h, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(decls))

    print(f"Wrote {out_c} and {out_h} ({len(images)} images)")


if __name__ == "__main__":
    main()
